import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ToastComponent from "@/components/ToastComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CatchMeApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="../assets/favicon.png"
          //type="image/<generated>"
          // sizes="<generated>"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-lightWhite`}
      >
        <ToastComponent />
        {children}
      </body>
    </html>
  );
}
